groups:
  - name: user-service-alerts
    rules:
      # 🚨 Alert: High Login Failures
      - alert: HighLoginFailures
        expr: increase(login_failures_total[5m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Login Failures"
          description: "More than 5 login failures detected within the last 5 minutes."

      # 🚨 Alert: High Login Attempts
      - alert: HighLoginAttempts
        expr: increase(login_requests_total[1m]) > 10
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "High Login Attempts Detected"
          description: "More than 10 login attempts detected within 1 minute."

      # 🚨 Alert: Slow API Response
      - alert: SlowAPIResponse
        expr: histogram_quantile(0.95, rate(http_response_time_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Slow API Response Time"
          description: "API response time exceeded 2 seconds for 95% of requests in the last 5 minutes."

      # 🚨 Alert: User-Service Down
      - alert: UserServiceDown
        expr: up{job="user-service"} == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "User-Service is Down"
          description: "The User-Service health endpoint is unreachable for more than 30 seconds."

      # 🚨 Alert: High API Failure Rate (>5 errors in 1 day, excluding login)
      - alert: HighAPIFailures
        expr: increase(api_errors_total[1d]) > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High API Failure Rate Detected"
          description: "More than 5 API errors (500 status) detected in the last 1 minute."


