global:
  scrape_interval: 5s  # 🔹 Ensure it is 5 seconds or less
  evaluation_interval: 5s  # 🔹 Ensure Prometheus evaluates rules frequently

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["ai-sre-server:4000"]
      scheme: http
      path_prefix: /
      timeout: 10s

rule_files:
  - alert_rules.yml
scrape_configs:
  - job_name: "user-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["user-service:5001"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]


## docker build -t custom-prometheus -f Dockerfile .  
## docker run -d --name prometheus -p 9090:9090 custom-prometheus


############################################