# Use Node.js 22.14.0 Alpine as the base image
FROM node:22.14.0-alpine AS base

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies (including Prisma)
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate Prisma client (Fixes Query Engine Issue)
RUN npx prisma generate

RUN npx prisma migrate dev --name init

RUN npm run seed

# Expose the correct port
EXPOSE 5002

# Command to run the application in development mode
CMD ["npm", "run", "dev"]
