FROM postgres:17-alpine

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=product-service-ms

# Expose the default PostgreSQL port
EXPOSE 5432

# Default command to run Postgres
CMD ["postgres"]
